### ISSUE TITLE
Param 'default' is ignored

### ISSUE THREAD

**Issue by bonstio** [BWilky/viewtimeout#12]
Given the following configuration, my dashboard still navigates to `home` and not to `weather`. Leading me to believe that 'default' is either not read or not used correctly.

```
view_timeout:
  timeout: true
  default: weather
  duration: 3000
```
